package pokemon.card.game;

import java.util.ArrayList;
import java.util.Collections;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skor1 = new javax.swing.JLabel();
        skor2 = new javax.swing.JLabel();
        oyuncu1kart1 = new javax.swing.JLabel();
        deste = new javax.swing.JLabel();
        oyuncu1kart2 = new javax.swing.JLabel();
        oyuncu2kart2 = new javax.swing.JLabel();
        oyuncu2kart3 = new javax.swing.JLabel();
        oyuncu2kart1 = new javax.swing.JLabel();
        oyuncu1kart3 = new javax.swing.JLabel();
        secim1 = new javax.swing.JButton();
        secim2 = new javax.swing.JButton();
        secim3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        oyuncu2kartsecilen = new javax.swing.JLabel();
        oyuncu1kartsecilen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        skor1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        skor1.setForeground(new java.awt.Color(0, 153, 255));
        skor1.setText("jLabel1");
        getContentPane().add(skor1);
        skor1.setBounds(590, 440, 70, 20);

        skor2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        skor2.setForeground(new java.awt.Color(0, 153, 255));
        skor2.setText("jLabel2");
        getContentPane().add(skor2);
        skor2.setBounds(600, 100, 60, 30);

        oyuncu1kart1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu1kart1.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu1kart1.setText("kart1");
        getContentPane().add(oyuncu1kart1);
        oyuncu1kart1.setBounds(150, 410, 121, 106);

        deste.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deste.setForeground(new java.awt.Color(51, 0, 204));
        deste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deste.png"))); // NOI18N
        deste.setText("deste");
        getContentPane().add(deste);
        deste.setBounds(590, 200, 210, 140);

        oyuncu1kart2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu1kart2.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu1kart2.setText("kart1");
        getContentPane().add(oyuncu1kart2);
        oyuncu1kart2.setBounds(300, 410, 121, 106);

        oyuncu2kart2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu2kart2.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu2kart2.setText("kart1");
        getContentPane().add(oyuncu2kart2);
        oyuncu2kart2.setBounds(300, 20, 121, 106);

        oyuncu2kart3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu2kart3.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu2kart3.setText("kart1");
        getContentPane().add(oyuncu2kart3);
        oyuncu2kart3.setBounds(430, 20, 121, 106);

        oyuncu2kart1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu2kart1.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu2kart1.setText("kart1");
        getContentPane().add(oyuncu2kart1);
        oyuncu2kart1.setBounds(160, 20, 121, 106);

        oyuncu1kart3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu1kart3.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu1kart3.setText("kart1");
        getContentPane().add(oyuncu1kart3);
        oyuncu1kart3.setBounds(450, 410, 121, 106);

        secim1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        secim1.setForeground(new java.awt.Color(255, 0, 0));
        secim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pokemon-Ash.png"))); // NOI18N
        secim1.setText("Sec");
        secim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim1ActionPerformed(evt);
            }
        });
        getContentPane().add(secim1);
        secim1.setBounds(110, 560, 130, 90);

        secim2.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        secim2.setForeground(new java.awt.Color(255, 0, 0));
        secim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pokemon-Ash.png"))); // NOI18N
        secim2.setText("Sec");
        secim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim2ActionPerformed(evt);
            }
        });
        getContentPane().add(secim2);
        secim2.setBounds(270, 560, 130, 90);

        secim3.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        secim3.setForeground(new java.awt.Color(255, 0, 0));
        secim3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pokemon-Ash.png"))); // NOI18N
        secim3.setText("Sec");
        secim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secim3ActionPerformed(evt);
            }
        });
        getContentPane().add(secim3);
        secim3.setBounds(430, 560, 130, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/devam1.png"))); // NOI18N
        jButton1.setText("Devam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 520, 160, 70);

        oyuncu2kartsecilen.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu2kartsecilen.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu2kartsecilen.setText("kart1");
        getContentPane().add(oyuncu2kartsecilen);
        oyuncu2kartsecilen.setBounds(300, 150, 121, 106);

        oyuncu1kartsecilen.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        oyuncu1kartsecilen.setForeground(new java.awt.Color(51, 0, 204));
        oyuncu1kartsecilen.setText("kart1");
        getContentPane().add(oyuncu1kartsecilen);
        oyuncu1kartsecilen.setBounds(300, 280, 121, 106);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 420, 90, 130);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 20, 90, 130);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 20, 90, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 160, 90, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 290, 90, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 420, 90, 130);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 420, 90, 130);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-623.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 20, 90, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-622.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 50, 140, 90);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pokemon-card-png-622.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 390, 130, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anaekran.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DevamEt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void secim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim1ActionPerformed
        ((InsanOyuncusu)oyuncu1).SonrakiSecimim(0);
    }//GEN-LAST:event_secim1ActionPerformed

    private void secim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim2ActionPerformed
        ((InsanOyuncusu)oyuncu1).SonrakiSecimim(1);
    }//GEN-LAST:event_secim2ActionPerformed

    private void secim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secim3ActionPerformed
        ((InsanOyuncusu)oyuncu1).SonrakiSecimim(2);
    }//GEN-LAST:event_secim3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
         new AnaEkran().setVisible(true);
         }
         });*/
    }
    Oyuncu oyuncu1, oyuncu2;
    ArrayList<Pokemon> cards = new ArrayList<Pokemon>();
    Pokemon oyuncu1SecilenKart, oyuncu2SecilenKart;
    boolean secimAsamasi = true;

    public void Oyun(int oyunTipi) {
        cards.add(new Pikachu());
        cards.add(new Bulbasaur());
        cards.add(new Charmander());
        cards.add(new Squirtle());
        cards.add(new Zubat());
        cards.add(new Psyduck());
        cards.add(new Snorlax());
        cards.add(new Butterfree());
        cards.add(new Jigglypuff());
        cards.add(new Meowth());

        Collections.shuffle(cards);

        if (oyunTipi == 1) {
            oyuncu1 = new BilgisayarOyuncusu("Bilgisayar1", 1, 0);
            secim1.setVisible(false);
            secim2.setVisible(false);
            secim3.setVisible(false);
        } else {
            oyuncu1 = new InsanOyuncusu("Insan", 1, 0);
        }

        oyuncu2 = new BilgisayarOyuncusu("Bilgisayar2", 2, 0);

        //3'er kart iki oyuncuyu da dağıtılır
        for (int i = 0; i < 3; i++) {
            Pokemon card = cards.remove(cards.size() - 1);
            oyuncu1.kartVer(card);

            card = cards.remove(cards.size() - 1);
            oyuncu2.kartVer(card);
        }
        EkranaYaz();
        /*while (oyuncu1.kartSayisi() > 0 && oyuncu2.kartSayisi() > 0) {

         }

         if (oyuncu1.getSkor() > oyuncu2.getSkor()) {
         System.out.println("oyuncu1 kazandi");
         } else if (oyuncu1.getSkor() == oyuncu2.getSkor()) {
         System.out.println("oyun berabere");
         } else {
         System.out.println("oyuncu2 kazandi");
         }*/
    }

    public void DevamEt() {

        if ((oyuncu1.kartSayisi() == 0 || oyuncu2.kartSayisi() == 0) && oyuncu1SecilenKart == null && oyuncu2SecilenKart == null) {
            BitisEkrani bitiesEkrani;
            if(oyuncu1.getSkor() > oyuncu2.getSkor())
                 bitiesEkrani = new BitisEkrani("Oyun bitti. Oyuncu1 kazandi!");
            else if(oyuncu1.getSkor() == oyuncu2.getSkor())
                bitiesEkrani = new BitisEkrani("Oyun bitti. oyun berabere!");
            else
                bitiesEkrani = new BitisEkrani("Oyun bitti. Oyuncu2 kazandi!");
            bitiesEkrani.setVisible(true);
            return;
        }
        
        if (secimAsamasi) {
            //oyuncular kart secer
            oyuncu1SecilenKart = oyuncu1.kartSecim();
            oyuncu2SecilenKart = oyuncu2.kartSecim();

        } else {
            //kartlar karsilastirilir
            if (oyuncu1SecilenKart.getHasarPuani() > oyuncu2SecilenKart.getHasarPuani()) {
                oyuncu1.setSkor(oyuncu1.getSkor() + 5);
            } else if (oyuncu2SecilenKart.getHasarPuani() > oyuncu1SecilenKart.getHasarPuani()) {
                oyuncu2.setSkor(oyuncu2.getSkor() + 5);
            }

            //kullanilan kartlar isaretlenir
            oyuncu1SecilenKart.setKartKullanildiMi(true);
            oyuncu2SecilenKart.setKartKullanildiMi(true);

            //yerde iki veya ikiden fazla kart varsa
            if (cards.size() >= 2) {
                //yeni kartlar dağıtılır
                Pokemon newCard = cards.remove(cards.size() - 1);
                oyuncu1.kartVer(newCard);

                newCard = cards.remove(cards.size() - 1);
                oyuncu2.kartVer(newCard);
            }
            
            oyuncu1SecilenKart = null;
            oyuncu2SecilenKart = null;
        }
        
        secimAsamasi = !secimAsamasi;
        EkranaYaz();
    }

    public void EkranaYaz() {
        SetDeste(cards.size() + " kart kaldi.");
        SetOyuncu1Skor(oyuncu1.getSkor());
        SetOyuncu2Skor(oyuncu2.getSkor());

        for (int i = 0; i < 3; i++) {
            Pokemon card = oyuncu1.kartGetir(i);
            if (card != null) {
                SetOyuncuKart(1, i, card.toString());
            } else {
                SetOyuncuKart(1, i, "Bos");
            }
        }

        for (int j = 0; j < 3; j++) {
            Pokemon card = oyuncu2.kartGetir(j);
            if (card != null) {
                SetOyuncuKart(2, j, card.toString());
            } else {
                SetOyuncuKart(2, j, "Bos");
            }
        }
        
        if(oyuncu1SecilenKart != null)
            oyuncu1kartsecilen.setText(oyuncu1SecilenKart.toString());
        else
            oyuncu1kartsecilen.setText("Bos");
        
        if(oyuncu2SecilenKart != null)
            oyuncu2kartsecilen.setText(oyuncu2SecilenKart.toString());
        else
            oyuncu2kartsecilen.setText("Bos");
    }

    public void SetOyuncuKart(int oyuncu, int kart, String value) {
        if (oyuncu == 1) {
            if (kart == 0) {
                SetOyuncu1Kart1(value);
            } else if (kart == 1) {
                SetOyuncu1Kart2(value);
            } else {
                SetOyuncu1Kart3(value);
            }
        } else {
            if (kart == 0) {
                SetOyuncu2Kart1(value);
            } else if (kart == 1) {
                SetOyuncu2Kart2(value);
            } else {
                SetOyuncu2Kart3(value);
            }
        }
    }

    public void SetOyuncu1Kart1(String value) {
        oyuncu1kart1.setText(value);
    }

    public void SetOyuncu1Kart2(String value) {
        oyuncu1kart2.setText(value);
    }

    public void SetOyuncu1Kart3(String value) {
        oyuncu1kart3.setText(value);
    }

    public void SetOyuncu2Kart1(String value) {
        oyuncu2kart1.setText(value);
    }

    public void SetOyuncu2Kart2(String value) {
        oyuncu2kart2.setText(value);
    }

    public void SetOyuncu2Kart3(String value) {
        oyuncu2kart3.setText(value);
    }

    public void SetOyuncu1Skor(int value) {
        skor1.setText("" + value);
    }

    public void SetOyuncu2Skor(int value) {
        skor2.setText("" + value);
    }

    public void SetDeste(String value) {
        deste.setText(value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deste;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel oyuncu1kart1;
    private javax.swing.JLabel oyuncu1kart2;
    private javax.swing.JLabel oyuncu1kart3;
    private javax.swing.JLabel oyuncu1kartsecilen;
    private javax.swing.JLabel oyuncu2kart1;
    private javax.swing.JLabel oyuncu2kart2;
    private javax.swing.JLabel oyuncu2kart3;
    private javax.swing.JLabel oyuncu2kartsecilen;
    private javax.swing.JButton secim1;
    private javax.swing.JButton secim2;
    private javax.swing.JButton secim3;
    private javax.swing.JLabel skor1;
    private javax.swing.JLabel skor2;
    // End of variables declaration//GEN-END:variables
}
